#'原名' = [ '译名', 出现次数 ]

"智秋" = ["智秋", 3140]
"ルミ" = ["瑠美", 1390]
"アイシャ" = ["艾莎", 639]
"シェリ" = ["雪莉", 454]
"裕也" = ["裕也", 401]
"男" = ["男人", 136]
"女の子" = ["女孩子", 89]
"灘" = ["滩", 82]
"リリス" = ["莉莉丝", 23]
"女" = ["女人", 21]
"ウエイトレス" = ["女服务员", 1]
"アイシャ…" = ["艾莎…", 1]
"店主" = ["店主", 1]

