# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)
gptDict = [
    # 语义标注

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },

    { org = "@", rep = "@", note = "游戏控制符，请保留，在游戏中遇到@时会停住，等待点击" },

    # ----------------------------------
    # 主要角色
    {org = "智秋", rep = "智秋", note = "人名，男性，全名“菅野智秋”（かんの ちあき），大学生，内心孤独，不善与人交往，本质上善良、有责任心，瑠美的收留者"},
    {org = "菅野", rep = "菅野", note = "人名姓氏，男性，智秋的姓氏"},
    {org = "チアキ", rep = "智秋", note = "人名，男性，智秋的称呼"},
    {org = "智秋さん", rep = "智秋先生", note = "人名，男性，智秋的称呼"},
    {org = "おにいちゃん", rep = "哥哥", note = "人名称呼，男性，一般是瑠美对智秋的称呼"},

    
    {org = "ルミ", rep = "瑠美", note = "人名，女性，少女，剧情前期真实身份不明，天真无邪，纯真烂漫，像孩子一样，非常坦率，善良，会关心他人，智秋的被保护者，实际上真实身份是非人类，属于诺斯费拉图（ノスフェラトゥ）一族"},
    {org = "ルミちゃん", rep = "小瑠美", note = "人名，女性，瑠美的称呼"},
    

    {org = "裕也", rep = "裕也", note = "人名，男性，全名“宫崎裕也”（宮崎 裕也），大学生，开朗、阳光，有些轻浮，但非常体贴朋友，智秋的挚友"},
    {org = "宮崎", rep = "宫崎", note = "人名姓氏，男性，裕也的姓氏"},
    {org = "裕也ちゃん", rep = "小裕也", note = "人名，男性，裕也的称呼"},

    
    {org = "アイシャ", rep = "艾莎", note = "人名，女性，少女，追杀诺斯费拉图的猎人（ハンター），金色长发，苍蓝眼眸，白肤（外国人长相），性格冷漠、寡言，拒人于千里之外"},
    {org = "アイシャさん", rep = "艾莎小姐", note = "人名，女性，艾莎的称呼"},
    
    {org = "シェリ", rep = "雪莉", note = "人名，女性，青年，非人类，属于诺斯费拉图（ノスフェラトゥ）一族，漆黑的长发，白瓷般的肌肤，血红色的眼眸，极其冷静和淡漠，言行举止带有一种超越年龄的威压感和说服力"},
    {org = "シェリさん", rep = "雪莉小姐", note = "人名，女性，雪莉的称呼"},

    {org = "おねえちゃん", rep = "姐姐", note = "人名称呼，女性，一般是瑠美对艾莎或者雪莉的称呼"},

    # ----------------------------------
    # 其他术语/角色
    {org = "灘", rep = "滩", note = "人名，男性，追杀诺斯费拉图的猎人（ハンター），目标是杀死瑠美，狂气，好战，实力和战绩远高于公认猎人"},

    {org = "ハンター", rep = "猎人", note = "以猎杀诺斯费拉图等非人存在为目标的组织，滩便是其中之一"},

    {org = "猟奇事件", rep = "猎奇事件", note = "发生在大学周边的不明连环杀人/失踪事件，死者遗体惨不忍睹且未被归还，可能与“非人”的存在有关。"},
    
    {org = "ノスフェラトゥ", rep = "诺斯费拉图", note = "对人类而言是“夜之一族”，非人类，包括吸血鬼、魔女、尸人、兽人、人鱼、鬼等。雪莉、瑠美、莉莉丝属于此族"},
    {org = "夜の一族", rep = "夜之一族", note = "诺斯费拉图的别称，非人一族"},
    
    {org = "リリス", rep = "莉莉丝", note = "人名，男性，非人类，属于诺斯费拉图（ノスフェラトゥ）一族，给人强烈印象的美貌男性，拥有血红色的瞳孔"},

    {org = "ロイヤルミルクティー", rep = "皇家奶茶", note = "饮品名"},

    {org = "御影池公園", rep = "御影池公园", note = "地点名"},
    {org = "みかげいけ", rep = "御影池", note = "地名"},
]
